"""Metaheuristic optimization parameters for the label assignment problem."""

GENETIC_POPULATION_SIZE = 60
GENETIC_GENERATIONS = 80
GENETIC_MUTATION_RATE = 0.2
GENETIC_TOURNAMENT = 3
ANNEALING_ITERATIONS = 1500
ANNEALING_INITIAL_TEMP = 1.0
ANNEALING_COOLING = 0.995
TABU_ITERATIONS = 200
TABU_NEIGHBORS_PER_STEP = 20
TABU_TENURE = 10
